version: '3.0'
services:
    mysql:
        image: mysql:5.7
        container_name: mysql
#        build:
#            context: .
#            dockerfile: Dockerfile.mysql
        hostname: mysql
        privileged: true
        restart: always
        ports:
            - 3306:3306/tcp
        networks:
            mysql_redis:
                aliases:
                    - mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./data/mysql:/var/lib/mysql
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
    redis:
        image: redis:4.0.6
        container_name: redis
        hostname: redis
        privileged: true
        restart: always
        ports:
            - 6379:6379/tcp
        networks:
            mysql_redis:
                aliases:
                    - redis
        volumes:
            - ./data/redis:/data:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
networks:
    mysql_redis:
