version: '3.0'
services:
    redis:
        image: redis:4.0.6
        container_name: redis
        hostname: redis
        privileged: true
        restart: always
        ports:
            - 6379:6379/tcp
        volumes:
            - ./data/redis:/data:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m
