version: '3'
services:
  cloud-demo:
    container_name: cloud-demo
    hostname: cloud-demo
    image: cloud-demo
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8090:8090
    networks:
      - cloud-net
    environment:
      TZ: 'Asia/Shanghai'
      SPRING_PROFILES_ACTIVE: dev
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 100m

# 该网络依赖于Cloud组件项目
networks:
  cloud-net:
    external: true
